server:
  port: 8082
  servlet:
    context-path:
name: wangzhaolin

spring:
  profiles:
    active: a
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_warehourse?serverTimezone=GMT%2B8
    username: root
    password: admin123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

